units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
          hotswap: true
  zones:
    main:
      key.padding: ky
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
          spread: kx
          row_overrides:
            bottom:
              column_net: P8
            home:
              column_net: P5
            top:
              column_net: P2
        ring:
          spread: kx
          stagger: 0.7ky
          row_overrides:
            bottom:
              column_net: P7
            home:
              column_net: P4
            top:
              column_net: P0
        middle:
          spread: kx
          stagger: 0.2ky
          row_overrides:
            bottom:
              column_net: P6
            home:
              column_net: P3
            top:
              column_net: P1
        index:
          spread: kx
          stagger: -0.3ky
          row_overrides:
            bottom:
              column_net: P15
            home:
              column_net: P19
            top:
              column_net: P21
        far:
          spread: kx
          stagger: -0.1ky
          row_overrides:
            bottom:
              column_net: P14
            home:
              column_net: P18
            top:
              column_net: P20
    thumbfan:
      anchor:
        ref: main_far_bottom
        shift: [-1.5kx, -1ky]
      columns:
        near:
          spread: kx
          rotate: 0
          origin: [-kx/2, -ky/2]
          key:
            column_net: P9
        home:
          spread: kx
          rotate: -15
          origin: [-kx/2, -ky/2]
          key:
            column_net: P10
        far:
          spread: kx
          rotate: -15
          origin: [-kx/2, -ky/2]
          key:
            column_net: P16
      rows:
        thumb:
outlines:
  exports:
    raw:
      - type: keys
        side: left
        size: [kx + px, ky + py]
        corner: px
    thumbfan_glue:
      - type: polygon
        points:
          - ref: main_far_bottom
            shift: [0.5kx + 0.5px, -0.5ky + 0.5py]
          - ref: thumbfan_far_thumb
            shift: [0.5kx - 0.5px, 0.5ky + 0.5py]
          - ref: thumbfan_far_thumb
            shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
          - ref: thumbfan_far_thumb
            shift: [-0.5kx + 0.5px, -0.5ky - 0.5py]
          - ref: thumbfan_near_thumb
            shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
          - ref: thumbfan_near_thumb
            shift: [-0.5kx - 0.5px, -0.5ky + 0.5py]
          - ref: thumbfan_near_thumb
            shift: [-0.5kx - 0.5px, 1.5ky + 0.5py]
          #- ref: thumbfan_near_thumb
          #  shift: [-0.5kx + 0.5px, +0.5ky + 0.5py]
          #- ref: main_pinkie_bottom
          #  shift: [3.5kx + 0.5px, -0.5ky - 0.5py]
          #- ref: main_pinkie_bottom
          #  shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
          #- ref: main_pinkie_home
          - ref: main_far_home
    patch_outer:
      - type: polygon
        points:
          - ref: main_ring_top
          - ref: main_ring_bottom
          - ref: main_pinkie_bottom
            shift: [-0.5 (kx + px), 0]
          - ref: main_pinkie_top
            shift: [-0.5 (kx + px), 0]
    patch_inner:
      - type: polygon
        points:
          - ref: main_far_top
            shift: [0.5 (kx + px), 0]
          - ref: main_far_bottom
            shift: [0.5 (kx + px), 0]
          - ref: main_index_bottom
          - ref: main_index_top
    controller_area:
      main:
        type: rectangle
        anchor:
          ref:
            - main_far_top
          shift: [0, -3.4 ky]
        size: [30.5, 65]
        corner: px
    keycaps:
      main:
        type: keys
        side: left
        size: [kx, ky]
        bound: false
        corner: 1
    keywell:
      main:
        type: outline
        name: raw
      patch_inner:
        type: outline
        name: patch_inner
        operation: add
      patch_outer:
        type: outline
        name: patch_outer
        operation: add
      thumbfan_cutout:
        type: outline
        name: thumbfan_glue
        operation: add
    base_outline:
      main:
        type: outline
        name: keywell
      controller:
        type: outline
        name: controller_area
        operation: add
    pcb:
      main:
        type: outline
        name: base_outline
    keycap_outlines:
      - type: keys
        side: left
        size: [1kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false
        corner: 1
    preview:
      [keycap_outlines]
    alignment_preview:
      main:
        type: outline
        name: base_outline
      keys:
        type: outline
        name: keycaps
        operation: stack
    combined_preview:
      main:
        type: outline
        name: raw
      patch_inner:
        type: outline
        name: patch_inner
        operation: stack
      patch_outer:
        type: outline
        name: patch_outer
        operation: stack
      thumbfan_glue:
        type: outline
        name: thumbfan_glue
        operation: stack
    pcb_with_keys:
      main: 
        type: outline
        name: pcb
      keys:
        type: outline
        name: preview
        operation: stack
pcbs:
  Owemekeeb:
    outlines:
      board:
        outline: pcb
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      mcu:
        type: promicro_pretty
        anchor:
          ref:
            - main_far_top
          shift: [20, -12.8]
          rotate: 270
      power:
        type: pcm12
        anchor:
          ref: main_far_bottom
          shift: [28.3, -5]
          rotate: 90
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true
      reset:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: main_far_bottom
          shift: [21.3, -5]
          rotate: 90
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: main_far_bottom
          shift: [12.5, -4]
          rotate: 0
      jlc_order_number:
        type: text
        anchor:
          ref:
            - main_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: right mirror
          layer: B.SilkS