units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  zones:
    main:
      key.padding: ky
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
          key:
            spread: kx
          rows:
            bottom:
              column_net: P8
            home:
              column_net: P5
            top:
              column_net: P2
        ring:
          key:
            spread: kx
            stagger: 0.7ky
          rows:
            bottom:
              column_net: P7
            home:
              column_net: P4
            top:
              column_net: P0
        middle:
          key:
            spread: kx
            stagger: 0.2ky
          rows:
            bottom:
              column_net: P6
            home:
              column_net: P3
            top:
              column_net: P1
        index:
          key:
            spread: kx
            stagger: -0.3ky
          rows:
            bottom:
              column_net: P15
            home:
              column_net: P19
            top:
              column_net: P21
        far:
          key:
            spread: kx
            stagger: -0.1ky
          rows:
            bottom:
              column_net: P14
            home:
              column_net: P18
            top:
              column_net: P20
    thumbfan:
      anchor:
        ref: main_far_bottom
        shift: [-1.5kx, -1ky]
      columns:
        near:
          key:
            spread: kx
            splay: 0
            origin: [-kx/2, -ky/2]
            column_net: P9
        home:
          key:
            spread: kx
            rotate: -15
            origin: [-kx/2, -ky/2]
            column_net: P10
        far:
          key:
            spread: kx
            rotate: -15
            origin: [-kx/2, -ky/2]
            column_net: P16
      rows:
        thumb:
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx + px, ky + py]
      corner: px
      bound: false
  thumbfan_glue:
    - what: polygon
      points:
        - ref: main_far_bottom
          shift: [0.5kx + 0.5px, -0.5ky + 0.5py]
        - ref: thumbfan_far_thumb
          shift: [0.5kx - 0.5px, 0.5ky + 0.5py]
        - ref: thumbfan_far_thumb
          shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
        - ref: thumbfan_far_thumb
          shift: [-0.5kx + 0.5px, -0.5ky - 0.5py]
        - ref: thumbfan_near_thumb
          shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
        - ref: thumbfan_near_thumb
          shift: [-0.5kx - 0.5px, -0.5ky + 0.5py]
        - ref: thumbfan_near_thumb
          shift: [-0.5kx - 0.5px, 1.5ky + 0.5py]
        #- ref: thumbfan_near_thumb
        #  shift: [-0.5kx + 0.5px, +0.5ky + 0.5py]
        #- ref: main_pinkie_bottom
        #  shift: [3.5kx + 0.5px, -0.5ky - 0.5py]
        #- ref: main_pinkie_bottom
        #  shift: [0.5kx - 0.5px, -0.5ky - 0.5py]
        #- ref: main_pinkie_home
        - ref: main_far_home
  patch_outer:
    - what: polygon
      points:
        - ref: main_ring_top
        - ref: main_ring_bottom
        - ref: main_pinkie_bottom
          shift: [-0.5 (kx + px), 0]
        - ref: main_pinkie_top
          shift: [-0.5 (kx + px), 0]
  patch_inner:
    - what: polygon
      points:
        - ref: main_far_top
          shift: [0.5 (kx + px), 0]
        - ref: main_far_bottom
          shift: [0.5 (kx + px), 0]
        - ref: main_index_bottom
        - ref: main_index_top
  controller_area:
    main:
      what: rectangle
      adjust:
        ref:
          - main_far_top
        shift: [0, -3.4 ky]
      size: [30.5, 65]
      corner: px
  keycaps:
    main:
      what: rectangle
      where: true
      size: [kx, ky]
      bound: false
      corner: 1
  keywell:
    main:
      what: outline
      name: raw
    patch_inner:
      what: outline
      name: patch_inner
      operation: add
    patch_outer:
      what: outline
      name: patch_outer
      operation: add
    thumbfan_cutout:
      what: outline
      name: thumbfan_glue
      operation: add
  base_outline:
    main:
      what: outline
      name: keywell
    controller:
      what: outline
      name: controller_area
      operation: add
  pcb:
    main:
      what: outline
      name: base_outline
  keycap_outlines:
    - what: rectangle
      where: true
      size: [1kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
      bound: false
      corner: 1
  preview:
    [keycap_outlines]
  alignment_preview:
    main:
      what: outline
      name: base_outline
    keys:
      what: outline
      name: keycaps
      operation: stack
  combined_preview:
    main:
      what: outline
      name: raw
    patch_inner:
      what: outline
      name: patch_inner
      operation: stack
    patch_outer:
      what: outline
      name: patch_outer
      operation: stack
    thumbfan_glue:
      what: outline
      name: thumbfan_glue
      operation: stack
  pcb_with_keys:
    main: 
      what: outline
      name: pcb
    keys:
      what: outline
      name: preview
      operation: stack
pcbs:
  owemekeeb:
    outlines:
      board:
        outline: pcb
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:          
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      mcu:
        what: promicro_pretty
        adjust:
          ref:
            - main_far_top
          shift: [20, -12.8]
          rotate: 270
      power:
        what: pcm12
        adjust:
          ref: main_far_bottom
          shift: [28.3, -5]
          rotate: 90
        params:
          from: pos  
          to: RAW
          reverse: true
      reset:
        what: b3u1000p
        adjust:
          ref: main_far_bottom
          shift: [21.3, -5]
          rotate: 90
        params:
          r1: RST  
          r2: GND
          reverse: true 
      bat:
        what: bat
        params: 
          neg: GND
        adjust:
          ref: main_far_bottom
          shift: [12.5, -4]
          rotate: 0
      jlc_order_number:
        what: text
        adjust:
          ref:
            - main_middle_home
          shift: [0, -0.25ky]
        params:
          text: JLCJLCJLCJLC
          layer: F.SilkS
          align: left