on: 
  workflow_call:
    inputs:
      keyboard:
        description: 'Keyboard to build'
        type: string
        default: 'owemekeeb'

name: Build
jobs:
  generate:
    strategy:
      matrix:
        keyboard: ${{ inputs.keyboard}}
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs
        run: node src/cli.js input/config-${{ matrix.keyboard }}.yaml
      - name: Export DSN for main PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: output/pcbs/${{ matrix.keyboard }}.kicad_pcb
          dsn_file: output/pcbs/${{ matrix.keyboard }}.dsn
      - name: Autoroute main PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: output/pcbs/${{ inputs.keyboard }}.dsn
          ses_file: output/pcbs/${{ inputs.keyboard }}.ses
      - name: Import SES into main PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: output/pcbs/${{ inputs.keyboard }}.kicad_pcb
          pcb_output_file: output/pcbs/${{ inputs.keyboard }}_routed.kicad_pcb
          ses_file: output/pcbs/${{ inputs.keyboard }}.ses
      - name: Run DRC on main PCB
        uses: ./.github/actions/run-drc
        with:
          pcb_file: output/pcbs/${{ matrix.keyboard }}.kicad_pcb
          drc_dir: output/pcbs/drc
        continue-on-error: true
      - name: Generate left image
        uses: ./.github/actions/draw-pcb
        with:
          pcb_file: output/pcbs/${{ matrix.keyboard }}.kicad_pcb
          image_dir: output/images
          image_name: left.png
          style: 'builtin:set-white-enig.json'
      - name: Generate right image
        uses: ./.github/actions/draw-pcb
        with:
          pcb_file: output/pcbs/${{ matrix.keyboard }}.kicad_pcb
          flags: '-b'
          image_dir: output/images
          image_name: right.png
          style: 'builtin:set-white-enig.json'
      - name: Export Gerbers for main PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/${{ matrix.keyboard }}.kicad_pcb
          gerbers_dir: output/gerbers/board
          flags: "--no-assembly --drc --nametemplate '${{ matrix.keyboard }}{}'"
        continue-on-error: true
      - name: Persist output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.keyboard }}-routed-pcbs-and-gerbers
          path: output
