name: 'Build owemekeeb'
on:
  workflow_dispatch:
  push:
    paths:
      - input/owemekeeb/config.yaml
jobs:
  #build:
  #  uses: ./.github/workflows/main.yml
  #  with:
  #    keyboard: '["owemekeeb"]'
  Fabrication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs
        run: node ../../src/cli.js .
        working-directory: input/owemekeeb
      - name: List files
        run: ls -al input/owemekeeb/output/pcbs
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          # Required - kibot config file
          config: config.kibot.yaml
          # optional - prefix to output defined in config
          dir: input/owemekeeb/output
          # optional - schematic file
          # schema: 'schematic.sch'
          # optional - PCB design file
          board: 'input/owemekeeb/output/pcbs/owemekeeb.kicad_pcb'
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: Owemekeeb
          path: input/owemekeeb/output